image: Ubuntu1804  # образ для сборки

stack: node 10  # окружение

branches:
  only:
    - master  # ветка git

cache: node_modules  # кеширование

install:
  - npm install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки

test_script:
  - npm run lint && npm test  # скрипт тестирования

environment:
  access_token:
  secure: dJS6qdyA6I7Dj0wGoYiUUpy1+QHPpkKJbHd+lPlG6sAM1EK3hwfxgzh4yPRx47qG

deploy_script:
  - git config --global credential.helper store
  - ps: Set-Content -Path "$HOME\.git-credentials" -Value "https://$($env:access_token):x-oauth-basic@github.com`n" -NoNewline
  - git config --global user.email "alexeenkov-frontend@yandex.ru"
  - git config --global user.name "Ilya"
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose